### ISSUE TITLE
terraform for rds-complete postgres

### ISSUE THREAD

**Issue by manishanaikmmn** [terraform-aws-modules/terraform-aws-rds#120]
how to create terraform module for db_subnet_group using non default subnets in non default vpc?

**Comment by antonbabenko** [comment]
I know, I am probably replying a bit too late but still.

Follow the example code [examples/complete-postgres](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/examples/complete-postgres/main.tf) and set values of `subnet_ids` and `vpc_security_group_ids` accordingly.

In the example, default VPC is used because it always present in the AWS account but in real projects non-default VPC is usually used.
