### ISSUE TITLE
aws_rds_cluster_parameter_group returns an error when passing in a list of parameters

### ISSUE THREAD

**Issue by pythian-ciciliani** [terraform-aws-modules/terraform-aws-rds#164]
Hi, I'm experiencing  an issue similar to the one that @Vlaaaaaaad reported.

**Terraform version:** 0.12.5
**AWS Provider version:** 2.27.0

Resource definition:
```hcl
resource "aws_rds_cluster_parameter_group" "cpg-west1-m" {
  name   = "cpg-medium"
  family = var.db_parameter_family
  provider    = "aws.uswest1"
  parameter = []
}

```

Error:
```
...

Error: Unsupported argument

  on aurora_mysql.tf line 18, in resource "aws_rds_cluster_parameter_group" "cpg-west1-m":
  18:   parameter = []

An argument named "parameter" is not expected here. Did you mean to define a
block of type "parameter"?
```
Is it possible to pass a list of parameters to this module or that option was deprecated? The end goal of course, is to pass a list of parameters as a parameter for this module.

Thanks!

_Originally posted by @gabocic in https://github.com/terraform-aws-modules/terraform-aws-rds/issues/111#issuecomment-530519656_

**Comment by antonbabenko** [comment]
Hi @pythian-ciciliani !

`aws_rds_cluster_parameter_group` is Aurora-specific resource but this module only works with normal RDS databases (MySQL, Postgres, Oracle, MSSQL). Consider checking out [terraform-aws-rds-aurora module](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora) for Aurora support.

As an error message says - `parameter` should be a block, so you should use `dynamic` to control them. See this, for example:

https://github.com/terraform-aws-modules/terraform-aws-rds/blob/4e654b5e8dc733392c213284183f90861ed79c2f/modules/db_parameter_group/main.tf#L12-L19

Closing this issue here because it is not related to this module.
