### ISSUE TITLE
Add support for encrypted master password

### ISSUE THREAD

**Issue by danielfm** [terraform-aws-modules/terraform-aws-rds#26]
The whole point of Terraform is to keep infrastructure configuration checked into source control, so having the database master password in plain text goes against this.

Would it be possible to use a KMS-encrypted string as the password?

**Comment by zacharya** [comment]
@danielfm It is, but just know that it will show up in your state file.  So unless you can use remote state and ensure that bucket or remote location is completely locked down, you're kind of back where you started.

This is a tough one to solve for RDS or just secrets in general with Terraform.

**Comment by antonbabenko** [comment]
As an alternative solution for keeping RDS password secret when using MySQL you can specify [`iam_database_authentication_enabled = true`](https://www.terraform.io/docs/providers/aws/r/db_instance.html#iam_database_authentication_enabled). This way your DB access will be managed using AWS IAM and won't be in a state file.

Also, you can set password as environment variable before running terraform, for example: `TF_VAR_password="mysecretpassword" terraform plan`

Closing this issue, because as @zacharya said secrets are written in state files and this module can't control this.

**Comment by tonglil** [comment]
> Also, you can set password as environment variable before running terraform, for example: TF_VAR_password="mysecretpassword" terraform plan

Just to clarify for anyone looking at this, setting the TF var via environment variable still means the secret is written in the state file. So if you are checking that in or have an open remote backend then it's going to be accessible.
