### ISSUE TITLE
Change the default of storage_encrypted to true

### ISSUE THREAD

**Issue by yi2020** [terraform-aws-modules/terraform-aws-rds#279]
I realize this may be a "breaking change", or viewed as such, but honestly, people are failing audits because of this, and one of the most "enjoyable" ways to spend your weekend is encrypting an existing RDS database (backup+restore, etc).

So, why not have it set to true by default? It doesn't cost anything ($ and cpu).

**Comment by antonbabenko** [comment]
There are no defaults that fit all but there are defaults that require less work to upgrade.

Sorry to hear that you spent the weekend in such an enjoyable way but the same would be for disabling decryption (there are cases when people want to disable it and don't deal with KMS, IAM, supported instance types). See [availability of Amazon RDS encryption](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html#Overview.Encryption.Availability).

Users must always review the parameters as they are configuring infrastructure. Assuming very smart defaults for the majority of cases is not something we can not do in these modules because there are drawbacks in both (eg, encrypting storage means using KMS which can cost money and dealing with IAM).

Closing this one.
