### ISSUE TITLE
huge delay with PR review and merges

### ISSUE THREAD

**Issue by daroga0002** [terraform-aws-modules/terraform-aws-rds#287]
I noticed that this module seems be maintained for long time (4 months) and there is 22 PRs for review which also contain some critical bug fixes. 

What we can do as community to increase velocity of developing and improving this module?

**Comment by antonbabenko** [comment]
We are the group of @terraform-aws-modules/triage-supporters well aware of this.

The reason is the lack of time from the reviewers' side to read the code, evaluate changes, run it, update examples, documentation, and comment back to the creators if there is anything they can do.

The best that community members can do is to help by reading and answer on issues, suggest closing some of them which are not relevant anymore, and verify that PRs are in good shape.

A couple of months ago we've had Terraform AWS modules Office Hours where we talked about some things related to this - https://www.youtube.com/playlist?list=PLvz1V_9d3uiufsJF6Romw_cyXBCqtNTGn

There was a plan to host such meetings regularly but I don't have time for that myself at the moment.

**Comment by daroga0002** [comment]
I tried this approach but without any permissions on repos this seems be useless. Generally speaking community:
- cannot tag issues
- cannot close issues
- cannot manage PRs

From other side community raising a huge amount of great PRs, but because they are not merged in reasonable time community will start abandoning this project.

I understand lack of time, but this is maybe time to open for new supporters and increase strength of maintainers?

**Comment by antonbabenko** [comment]
In order to bring new supporters on board, we need to make sure that he/she has been helping the project(s) for a while.
