### ISSUE TITLE
Call to function "coalesce" failed: no non-null, non-empty-string arguments.

### ISSUE THREAD

**Issue by petrmvala** [terraform-aws-modules/terraform-aws-rds#305]
## Description

In the latest versions this module fails on terraform plan. If there is any other info I should provide, let me know. I'm going to fix my deployment now.

## Versions
 - Terraform:
0.14.7
 - Provider(s):
hashicorp/aws v3.30.0
hashicorp/cloudinit v2.2.0
hashicorp/dns v3.1.0
 - Module:
2.25 (by the way it would be useful to have this version printed automatically), 2.22 works fine

## Reproduction
`terraform plan`

### Code Snippet to Reproduce
```
module "db" {
  source  = "terraform-aws-modules/rds/aws"
  version = "2.22"

  identifier = var.tags.Cluster

  engine            = local.engine
  engine_version    = var.engine_version
  instance_class    = var.instance_class
  allocated_storage = var.allocated_storage

  name     = var.name
  username = var.username
  password = var.password
  port     = var.port

  vpc_security_group_ids = var.vpc_security_group_ids
  subnet_ids             = var.subnet_ids

  maintenance_window = "Mon:00:00-Mon:03:00"
  backup_window      = "03:00-06:00"

  multi_az = true

  tags = var.tags

  create_db_option_group    = false
  create_db_parameter_group = false
}
```

## Expected behavior
No errors

## Actual behavior
```
Error: Error in function call

on .terraform/modules/presto_cluster.rds.db/main.tf line 5, in locals:
5:   parameter_group_name_id = coalesce(var.parameter_group_name, module.db_parameter_group.this_db_parameter_group_id)
   |----------------
   | module.db_parameter_group.this_db_parameter_group_id is ""
   | var.parameter_group_name is ""

Call to function "coalesce" failed: no non-null, non-empty-string arguments.
```

**Comment by Dasnap** [comment]
I have also noticed the same problem this morning. Oddly, it seems to only crop up for one of my uses of the module, although that could just be the errors not being descriptive enough. Fixing one may then cause another to show its error etc.

**Comment by bryantbiggs** [comment]
hi @petrmvala / @Dasnap - this is from #304 where we are trying to correct the `name` and `name_prefix` usage of the submodules. because you are telling the module to not create the parameter group, you need to add the value `parameter_group_name` with the parameter group that you are using. you can see an example here https://github.com/terraform-aws-modules/terraform-aws-rds/blob/77c5e444c1aa5ef9798cb99cc40b4813891dbd5e/examples/groups/main.tf#L137 - this shows the module as not creating the option group or parameter group, and instead you provide those values to the module because they already have been created elsewhere. let me know if this clears up your issue

**Comment by petrmvala** [comment]
Exactly as @bondezbond writes.

In addition to that, I would point out that this is a breaking change while there is only minor version update. Is there any way I can help with testing?
I don't see any tests in this repo and the fact that you made 3 releases during past 24 hours is a bit unsettling.

**Comment by bryantbiggs** [comment]
@bondezbond / @petrmvala no no - its hard to speak to exactly what you are seeing/saying without seeing your configurations.

If you want to pass a parameter group or option group that was created outside of the module, reference this example here https://github.com/terraform-aws-modules/terraform-aws-rds/blob/77c5e444c1aa5ef9798cb99cc40b4813891dbd5e/examples/groups/main.tf#L129 - specifically lines 134-138

If you want to let the module create the parameter/option groups, reference this example https://github.com/terraform-aws-modules/terraform-aws-rds/blob/77c5e444c1aa5ef9798cb99cc40b4813891dbd5e/examples/groups/main.tf#L55 - specifically lines 60-62

This example is what most will want to reference as its the closest to what the defaults were previously. If you want to avoid changes, you can pass the name as the module was using it previously before the updates to make corrections, like the following (where `var.identifier` is the value you are providing to the module:

```hcl
  option_group_name = "${var.identifier}-"

  parameter_group_name = "${var.identifier}-"
```

And lastly, if you want to let the module create the parameter/option groups but WITHOUT using the prefix strategy, see this example here https://github.com/terraform-aws-modules/terraform-aws-rds/blob/77c5e444c1aa5ef9798cb99cc40b4813891dbd5e/examples/groups/main.tf#L91 - specifically lines 96-100

@petrmvala we do have tests in the repository, they are the projects located under the `examples/*`. This is what the maintainers use to validate changes as well as correctness for the codebase. These changes were made because users are asking for them - to improve the way the modules are used and to allow them to use them in a broader/more applicable manner. previously the module was making strong assumptions about names and prefix strategies and after putting off these changes for some time, we are moving forward with those corrections. Is it somewhat disruptive? Yes, unfortunately. Users are urged to pin their versions so that they can control when they are ready to advance the module version in use, this is standard. We try to avoid disruptive changes as much as possible but eventually its inevitable. 

If you all are able to share your configs and the issues you are seeing, we are glad to help get you sorted and headed down the right path - these changes are honestly very minimal if you understand terraform and what the output is telling you.

**Comment by bryantbiggs** [comment]
@bondezbond correct - users wanted more control over the name/naming conventions used and that is what we are now allowing. before, option and parameter groups were defaulting to using `${var.identifier}-` which was assigned to the `name_prefix` attribute of either resource.

however, now I see what you are saying in terms of letting the aws provider chose the default option and parameter groups. I'm not sure how this worked before but I can have a PR open to correct this behavior - thank you for pointing that out!
