### ISSUE TITLE
Add `count` like parameter to set a number of db_instances to create

### ISSUE THREAD

**Issue by jordiclariana** [terraform-aws-modules/terraform-aws-rds#46]
Hi guys!

Would it make sense to enable the creation of several db-instances with a single call of the module? These instances will share subnet_groups and parameters_groups.

The use case I'm thinking of is when you have a RDS master and you want to create X slaves from it. Instead of repeating the module call for every slave, you specify a parameter so the module do it for you.
It is also convenient to do it this way instead of calling the module several times when you have different environments (or workspaces) and a different number of slaves per environment. For instance, for production I would like to have 4 slaves, but for a test environment it is enough with just 1 slave. Passing the number of slave using a variable makes its way easier to achieve this.

What do you think? I can make the changes if you think is a good idea. Also I would like to know what would be the better variable name for this (I would not use `count` as it can be a reserved word for modules in the future).

The main problem here will be the outputs for the _submodule_ db_instance, they will be a list instead of a string, and this will break backward compatibility...

I guess this should be considered for a major version release.

**Comment by antonbabenko** [comment]
Hi! Thanks for the proposal. Here is what I think about this. It is a good idea for [ec2-instance module](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/) because it creates equal resources. Though it is not a great idea for RDS, because:
1. If `apply_immediately` is set to `true` all RDS instances will become unavailable at once.
1. If `final_snapshot_identifier` is set to not empty string it will fail to create snapshots because the one with the same name already exists.
1. Common for all conditional things in Terraform modules. Adding `count` makes code uglier and harder to test.

Talking from a practical point of view I want to say that infrastructure code is easier to read and understand when there is no logic related to `count` and following **what you see is what you get** principle helps with this. It is better to write several `module` blocks with same properties than guessing based on what environment/workspace you are working at.

Let's keep it open for some time to hear what other people think about your proposal.

PS: Also, I don't think that the concept of workspaces should be used to separate infrastructure - it hides details, which are important.
