### ISSUE TITLE
Thoughts about a local-exec provisioner in aws_db_instance

### ISSUE THREAD

**Issue by mazzy89** [terraform-aws-modules/terraform-aws-rds#49]
I have to support an use case where I need to run immediately after the database is created a bunch of SQL script. I was thinking to use `local-exec` provisioner. Any objections if I create a PR to add to the `aws_db_instance` resource the `local-exec` provisioner. Of course it would be conditionally

**Comment by antonbabenko** [comment]
You can probably get the same by using [null_resource](https://www.terraform.io/docs/provisioners/null_resource.html) with `local-exec`.

I would not prefer to connect provisioners in this module because there are several types of provisioners and making it really conditionally is not going to work (can't use `count` in provisioner block). Closing this issue now.
