### ISSUE TITLE
Risky version pins

### ISSUE THREAD

**Issue by sftim** [terraform-aws-modules/terraform-aws-rds#524]
## Description

This module seems to put its users at risk from breaking changes that result from major version bumps in its dependencies.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 6.3.0

- Terraform version:
`~> 2.0`
- Provider version(s):
`6.0` for AWS

## Reproduction Code [Required]

You will need a time machine. The risk exists but there is no Terraform 2.0 nor any AWS provider plugin 6.0

## Expected behavior

When there is a breaking change, this module defends against it.

## Actual behavior

You will need a time machine. The risk exists but there is no Terraform 2.0 nor any AWS provider plugin 6.0

Major version changes can result in _any_ outcome; it is Undefined Behavior.

However it is quite likely that AWS will release a version 6 plugin, and it's hard to know whether the breaking change from that release will have a business critical impact.

## Additional context

I opened https://github.com/terraform-aws-modules/terraform-aws-rds/pull/518 that was closed unmerged. I'm opening this to track the won't fix status and to collect upvotes if people do want to request it.

**Comment by bryantbiggs** [comment]
I'm curious to understand why you feel that the module needs to provide this restriction as opposed to users specifying their pinned versions?

From our perspective, we are specifying the minimum required version requirements for the module - which, if I understand correctly, is what most projects follow as well.

**Comment by sftim** [comment]
> If dependencies are specified too loosely, you will inevitably be bitten by version promiscuity (assuming compatibility with more future versions than is reasonable)

&mdash; https://semver.org/

I see it as good software engineering practice.

**Comment by sftim** [comment]
It's good to defend in depth against major version bumps, but: if you fix all _your_ code to work with the provider's new major version, and it applies cleanly, you might incorrectly assume that everything still works.

And then you find out that your snapshots aren't encrypted, or something, and you weep.

**Comment by bryantbiggs** [comment]
> I see it as good software engineering practice.

I don't disagree with this as a whole - but why is that our responsibility and not the users? Said differently, even if we do as you are suggesting here, users are not protected if they do not pin versions in their implementation. We aim to follow semver as much as possible, in our interpretation as it applies to Terraform, but we are still human and humans can make mistakes which is why we always recommend users to pin the versions of the resources/modules/providers that they are utilizing

>It's good to defend in depth against major version bumps, but: if you fix all your code to work with the provider's new major version, and it applies cleanly, you might incorrectly assume that everything still works.
And then you find out that your snapshots aren't encrypted, or something, and you weep.

I disagree here and think this is a flawed approach to Terraform - you evaluate the plan before letting Terraform apply. If you are not evaluating the changes that Terraform is proposing, making module authors pin versions isn't going to solve anything here

The common denominator is that users need to pin their version requirements in their implementation and evaluate the changes prior to letting Terraform apply them
