### ISSUE TITLE
kms_key_id should be named kms_key_arn

### ISSUE THREAD

**Issue by Doerge** [terraform-aws-modules/terraform-aws-rds#76]
The `aws_kms_key` resource have to outputs: `key_id` and `arn`. I got confused by the naming of the arg `kms_key_id` in this module because it's not the `key_id` of `aws_kms_key` but the `arn` (at least that's what I understood from the error message).

Example:
```
resource "aws_kms_key" "my_key" {
  description = "my key"
}

module "db" {
  source = "terraform-aws-modules/rds/aws"

  # fails:
  kms_key_id = "${aws_kms_key.my_key.key_id}"
  # works
  kms_key_id = "${aws_kms_key.my_key.arn}"
  [...]
}
```
 Would it make sense to rename `kms_key_id` to `kms_key_arn`? Or am I perhaps doing something completely wrong here?

**Comment by antonbabenko** [comment]
Yes, it gives some confusion to me also.

It is called `kms_key_id` because this is how it is called inside [aws_db_instance resource](https://www.terraform.io/docs/providers/aws/r/db_instance.html#kms_key_id) and there is very little reason to rename it from `key_id` to `key_arn` in just one place (this module) and not in all, which also include:
1. Terraform AWS provider - https://github.com/terraform-providers/terraform-provider-aws/blob/73324f65bac1b15e2be240ed580564a62a969ad1/aws/resource_aws_db_instance.go#L363-L369

2. AWS SDK - https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBInstanceInput.SetKmsKeyId

**Comment by FernandoMiguel** [comment]
I've lose a couple of hours on this more than once, before I remember that key is not key but something else

**Comment by sapher** [comment]
It's ridiculous XD
