### ISSUE TITLE
use of "lifecycle" metaparameter not possible

### ISSUE THREAD

**Issue by audiolomb** [terraform-aws-modules/terraform-aws-rds#80]
It looks like the metaparameter "lifecycle" can't be used.
Is this something that can be added?

Thank you

**Comment by antonbabenko** [comment]
You are right, there are almost no `lifecycle` meta parameters in this module because there can be various situations when user don't want to use them. It is not possible to have them conditionally in Terraform 0.11, so we don't have them in this module.

Could provide some details regarding what you are trying to do?

**Comment by audiolomb** [comment]
Sure!
This is a current issue I am having. I have a bunch of non-encrypted RDS instances and need to encrypt them.

This means: creating a snapshot, creating an encrypted copy of the snapshot, and then creating a brand new instance by snapshot restore.

The idea would be to instruct the module (via lifecycle) to do something like this:

lifecycle {
    ignore_changes = [
      "snapshot_identifier",
    ]
}

So the first time the instance would be created and then if the snap changes (deletion, for example), there is no risk of having Terraform destroy the resource.

Does this make sense?
Thank you!

**Comment by gschaffer-cxn** [comment]
HI!

I know I am late to the party, but here is my usecase:
ignore_changes = [
engine_version
]

When allow_minor_version_upgrade is set to true.

**Comment by zuver** [comment]
We have almost the exact same use case as @audiolomb and I currently don't see a path forward that doesn't involve forking this repository and adding a custom `ignore_changes` to the module.

Is there a suggested pattern that we could use that would have the effect of _not_ re-creating the database instance just because some attribute changed?

**Comment by antonbabenko** [comment]
In Terraform 0.12 (as of today) it is still not possible to parametrize `lifecycle` and one of the best options to avoid constant recreation of resources is to fork this repo and set your own `ignore_changes`.

Another way to avoid recreation is to split your Terraform configurations into separate layers/stacks/folders or to limit the scope by using `-target`, for e.g. `terraform apply -target=...`.

As soon as things change in Terraform, we will make sure to update many of Terraform AWS modules to support it.

I am going to close this issue because there is not much we can do at the moment.

**Comment by larstobi** [comment]
I think there is also an argument to make this an unconditional opinionated parameter. Let me elaborate.

PostgreSQL says:
https://www.postgresql.org/support/versioning/
“We always recommend that all users run the latest available minor release for whatever major version is in use.”

“Upgrading to a minor release does not normally require a dump and restore; you can stop the database server, install the updated binaries, and restart the server. For some releases, manual changes may be required to complete the upgrade, so always read the release notes before upgrading. ”

“While upgrading will always contain some level of risk, PostgreSQL minor releases fix only frequently-encountered bugs, security issues, and data corruption problems to reduce the risk associated with upgrading. For minor releases, the community considers not upgrading to be riskier than upgrading.”

I have not investigated how MySQL regards this, but we sure can do that.

As far as PostgreSQL is concerned, it is recommended to always do minor patching, and as AWS indeed provides this automatically, it is the default behaviour, and indeed the Terraform AWS provider even has it enabled as default: 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#auto_minor_version_upgrade
“(Optional) Indicates that minor engine upgrades will be applied automatically to the DB instance during the maintenance window. Default true.”

It is a blocking problem, as we are unable to use the module for fear of DB destroys. Without the possibility of a conditional block, I think this is a choice that has to be made by this module for us.
